# cat-id, but no reference for religion
#
# - have a religion(P140) = catholic church (Q9592) and a catholic-hierarchy-id (P1047)
# - but do not have a reference for their religion
#
# todo: set catholic-hierarchy and their id as reference for their religion 

# cat-id


SELECT ?item ?itemLabel ?religion ?cathid WHERE {
  ?item wdt:P140 wd:Q9592.
  ?item wdt:P140 ?religion;
    wdt:P1047 ?cathid;
    wdt:P569 ?birth;

  FILTER(NOT EXISTS {
    ?item p:P140 _:b75.
    _:b75 ps:P140 ?relsub;
      prov:wasDerivedFrom _:b74.
    _:b74 pr:P1047 ?relref.
  })

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en". }
}
ORDER BY DESC (?birth)
LIMIT 100
