# cat-id, but no reference for religion
#
# - have a religion(P140) = catholic church (Q9592) and a catholic-hierarchy-id (P1047)
# - have a position held(P39) = catholic archbishop (Q48629921)

# - but do not have a reference for that position held
#
# todo: set catholic-hierarchy and their id as reference for their position 
# 

SELECT ?item ?itemLabel ?religion ?cathid ?rel2sub WHERE {
  ?item wdt:P39 wd:Q48629921;
    wdt:P140 wd:Q9592, ?religion;
    wdt:P1047 ?cathid;
    wdt:P569 ?birth.
  
  FILTER(NOT EXISTS {
    ?item p:P39 _:b80.
    _:b80 ps:P39 ?relsub2;
      prov:wasDerivedFrom _:b30.
  })
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en". }
}

ORDER BY DESC (?birth)
LIMIT 100
